name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/nbdev-ci@master]
  pypi:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: pypi 
      uses: fastai/workflows/nbdev-pypi@master
      if: startsWith(github.ref, 'refs/tags/')
